config/routes.rb
CocoaDesserts::Application.routes.draw do

  root to: "static_pages#inicio"
  
  match "/contacto", to: "static_pages#contacto"
  match "/pedidos", to: "static_pages#pedidos"
 
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def inicio
	end

	def pedidos
	end

	def contacto
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Cocoa Desserts!"
    if page_title.empty?
      base_title
    else
      "#{base_title} - #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<div id="footer">
	<%= link_to image_tag("http://www.ok.gov/ltgovernor/images/Facebook-icon.png", alt: "Facebook page", align: "center", style:"display: block; margin: auto; cursor: pointer", width: "50px", height: "50px"), "http://www.facebook.com/pages/Cocoa-Desserts/310964798918355" %>
</div>

app/views/layouts/_header.html.erb
<div id="header", media="screen and (max-device-width: 480px)">
	<div id="navbar"> 
		<ul> 
			<li><%= link_to "Inicio", root_path, class: (current_page?(root_path))? "selectedTab" : nil %></li> 
			<li><%= link_to "Catálogo", "#", class: (current_page?("#"))? "selectedTab" : nil %></li>
			<li><%= link_to image_tag("logo.jpg", alt: "Inicio", id: "logo"), root_path %></li>
			<li><%= link_to "Pedidos", pedidos_path, class:  (current_page?(pedidos_path))? "selectedTab" : nil %></li>
			<li><%= link_to "Contacto", contacto_path, class:  (current_page?(contacto_path))? "selectedTab" : nil %></li>
		</ul>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	<title><%= full_title(yield(:title)) %></title>
	<%= stylesheet_link_tag    "application", :media => "all" %>
  	<%= javascript_include_tag "application" %>
  	<%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" %>
	<%= javascript_include_tag "http://code.jquery.com/ui/1.8.19/jquery-ui.min.js" %>
  	<%= csrf_meta_tags %>
	<meta http-equiv=Content-Type content=text/html; charset=ISO-8859-1>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div id="bg">
			<div id="content">
				<%= yield %>
			</div>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>

app/views/static_pages/contacto.html.erb
<% provide(:title, 'Contacto') %>
<p class="niceText">¡Ll&aacute;manos!</p>
<span class="niceText">Horarios:</span>
<span class="blueText" style="font-size: 125%;">Lunes a Viernes: 8:00am a 8:00pm</span>
<span class="blueText" style="font-size: 125%;">S&aacute;bado y Domingo: 8:00am a 7:00pm</span>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<span class="blueText" style="font-size: 150%;">Tel&eacute;fono: 8007-03-31</span>
<span class="niceText">Email:<%= link_to "cocoadesserts@hotmail.com", "mailto:cocoadesserts@hotmail.com", style: "text-decoration: underline;" %></span>

app/views/static_pages/inicio.html.erb
<% provide(:title, 'Inicio') %>
<p class="niceText">Bienvenido a Cocoa Desserts!</p>
<% link_to "", "#", id: "slide-next"%>
<% link_to "", "#", id: "slide-prev"%>
<div id="slider">
	<div class="slide cs-activeSlide"> 
		<%= image_tag("pastelFresasMango.jpg", alt: "Pastel de Fresas con Mango", width: "400px", height: "300px") %></div>
	<!-- Slide with Link --><!-- 
	<div class="slide"> <img src="../Images/payDurazno.jpg" width="400px" height="300px"/> </div>
	<div class="slide"> <img src="../Images/pastelFresas.jpg" width="400px" height="300px"/> </div>
	<div class="slide"> <img src="../Images/payTortuga.jpg" width="400px" height="300px"/> </div> -->
</div>
<!-- If you want to use Captions -->
<div class="slide-captions">
	<div class="sl-descr"></div>
	<div class="sl-descr"></div>
	<!-- Empty caption-->
	<div class="sl-descr"></div>
	<div class="sl-descr"></div>
</div>
<div class="caption"></div>
<!-- If you want to use Pagination -->
<div class="pagination">
	<span class="slider-pagination"></span>
	<span class="slider-pagination"></span>
	<span class="slider-pagination"></span>
	<span class="slider-pagination"></span>
</div>

app/views/static_pages/pedidos.html.erb
<form>
	<table>
		<tr>
			<td style="padding-left: 50px; padding-right: 50px;">
				<!-- <div>
					<?php if(isset($tiposDePostres)) { ?>
						<span style="position: fixed;"><img width="100px" height="100px"/></span>
						<?php foreach($tiposDePostre as $tipoDePostre) { ?>
							<fieldset class="fieldPedidos" style="height: 200px; overflow: scroll;">
								<legend><?php echo $tipoDePostre['Nombre']; ?></legend>
								<table class="tablaPedidos">
									<tbody>
										<tr>
											<td>
												<select>
													<option value="0">Selecciona un producto</option>
													<?php foreach($postres[$tipoDePostre['ID_TipoPostre']] as $postre) { echo "<option value='".$postre['ID_Articulo']."'>".$postre['Nombre']."</option>"; } ?>
												</select>
											</td>
											<td>
												<input type="text" placeholder="Cantidad" size="5" maxlength="3"/>
											</td>
											<td>
												<input type="text" placeholder="Total" style="display: block;" />
											</td>
										</tr>
										<tr>
											<td align="left"><input type="button" value="M&aacute;s" /></td>
										</tr>
									</tbody>
								</table>
							</fieldset>
						<?php } ?>
					<?php } else { echo "<div id='contentDatos' class='niceText' style='font-size: 60%;'><center>Ocurri&oacute; un error en la p&aacute;gina, por favor intenta m&aacute;s tarde! =)</center></div>";  } ?>
				</div> -->
				<div id='contentDatos' class='niceText' style='font-size: 60%;'>
					<center>Nuestro catálogo está vacío en estos momentos, por favor intenta más tarde! =)</center>
				</div>
			</td>
			<td style="padding-left: 50px; padding-right: 50px;">
				<div id="frameDatos">
					<div id="contentDatos">
						<center class="niceText" style="font-size: 450%;">Tus datos:</center>
						<br />
						<br />
						<br />
						<table>
							<tr><td class="textField nice">Nombre:</td><td><input id="nombre" name="nombre" type="text" /></td>
							<tr><td class="textField nice" >Correo:</td><td><input id="email" name="email" type="text" /></td>
							<tr><td class="textField nice" >Telefono:</td><td><input id="phone" name="phone" type="text" /></td>
							<tr><td class="textField nice" >Comentarios:</td></tr>
						</table>
						<textarea style="width: 275px; height: 100px; margin: 2px;"></textarea>
						<br />
						<br />
						<input type="submit" value="Enviar Pedido"/>
					</div>
				</div>
			</td>
		</tr>
	</table>
</form>